#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;
using static Kingfisher.KEmoji.Libs.KUtils;

namespace Kingfisher.KEmoji
{
    internal static class KEmojiCodeGen
    {
        #region Field

        private const string NewLine = "\n";
        private const string Indent = "    ";
        private const string OpenBrace = "{";
        private const string CloseBrace = "}";

        private const string HeaderRule = "//------------------------------------------------------------------------------";
        private const string GeneratedOpen = "// <auto-generated>";
        private const string GeneratedClose = "// </auto-generated>";
        private const string GeneratedByFormat = "//     Generated by K-Emoji from {0}.";
        private const string GeneratedWarning = "//     Changes are lost the next time the atlas is generated.";

        private const string NamespaceFormat = "namespace {0}";
        private const string ClassFormat = "public static class {0}";
        private const string ConstantFormat = "public const string {0} = \"{1}\";";

        private const string FallbackConstantName = "SPRITE";
        private const string UniqueSuffixFormat = "{0}_{1}";
        private const int FirstUniqueSuffix = 1;
        private const char ConstantSeparator = '_';

        private const string Backslash = "\\";
        private const string EscapedBackslash = "\\\\";
        private const string Quote = "\"";
        private const string EscapedQuote = "\\\"";

        private const string JsonExtension = ".json";
        private const string PngExtension = ".png";
        private const string GeneratorName = "Kingfisher.KEmoji";
        private const string DocumentVersion = "1.0";
        private const string PixelFormat = "RGBA8888";
        private const string DocumentScale = "1";
        private const float CenterPivot = .5f;
        private const int NoOffset = 0;

        #endregion

        #region Constants Script

        public static bool WriteConstants(KEmojiAtlas.Result atlas, KEmojiData data)
        {
            var relativePath = data.scriptPath.ToProjectRelativePath();

            if (string.IsNullOrEmpty(relativePath)) return false;

            return WriteIfChanged(relativePath, BuildConstants(atlas, data));
        }

        private static string BuildConstants(KEmojiAtlas.Result atlas, KEmojiData data)
        {
            var builder = new StringBuilder();
            var hasNamespace = !string.IsNullOrEmpty(data.scriptNamespace);
            var indent = hasNamespace ? Indent : string.Empty;

            AppendHeader(builder, data);

            if (hasNamespace)
            {
                builder.Append(string.Format(NamespaceFormat, data.scriptNamespace)).Append(NewLine);
                builder.Append(OpenBrace).Append(NewLine);
            }

            builder.Append(indent).Append(string.Format(ClassFormat, data.scriptClassName)).Append(NewLine);
            builder.Append(indent).Append(OpenBrace).Append(NewLine);

            var usedNames = new HashSet<string>();

            for (var i = 0; i < atlas.Placements.Count; i++)
            {
                var spriteName = atlas.Placements[i].Name;

                builder.Append(indent).Append(Indent);
                builder.Append(string.Format(ConstantFormat, ToUniqueConstantName(spriteName, usedNames), Escape(spriteName)));
                builder.Append(NewLine);
            }

            builder.Append(indent).Append(CloseBrace).Append(NewLine);

            if (hasNamespace)
            {
                builder.Append(CloseBrace).Append(NewLine);
            }

            return builder.ToString();
        }

        private static void AppendHeader(StringBuilder builder, KEmojiData data)
        {
            builder.Append(HeaderRule).Append(NewLine);
            builder.Append(GeneratedOpen).Append(NewLine);
            builder.Append(string.Format(GeneratedByFormat, data.atlasPath)).Append(NewLine);
            builder.Append(GeneratedWarning).Append(NewLine);
            builder.Append(GeneratedClose).Append(NewLine);
            builder.Append(HeaderRule).Append(NewLine);
            builder.Append(NewLine);
        }

        private static bool WriteIfChanged(string relativePath, string content)
        {
            var absolutePath = relativePath.ToAbsolutePath();

            if (File.Exists(absolutePath) && File.ReadAllText(absolutePath) == content) return false;

            EnsureAssetFolder(relativePath.GetParentPath());

            File.WriteAllText(absolutePath, content);

            AssetDatabase.ImportAsset(relativePath);

            return true;
        }

        private static string ToUniqueConstantName(string spriteName, HashSet<string> usedNames)
        {
            var baseName = ToConstantName(spriteName);
            var uniqueName = baseName;
            var suffix = FirstUniqueSuffix;

            while (!usedNames.Add(uniqueName))
            {
                uniqueName = string.Format(UniqueSuffixFormat, baseName, suffix);

                suffix++;
            }

            return uniqueName;
        }

        private static string ToConstantName(string spriteName)
        {
            var builder = new StringBuilder(spriteName.Length);

            for (var i = 0; i < spriteName.Length; i++)
            {
                var character = spriteName[i];

                if (!char.IsLetterOrDigit(character))
                {
                    AppendSeparator(builder);

                    continue;
                }

                if (char.IsUpper(character) && i > 0 && !char.IsUpper(spriteName[i - 1]))
                {
                    AppendSeparator(builder);
                }

                builder.Append(char.ToUpperInvariant(character));
            }

            while (builder.Length > 0 && builder[builder.Length - 1] == ConstantSeparator)
            {
                builder.Length--;
            }

            if (builder.Length == 0) return FallbackConstantName;

            if (char.IsDigit(builder[0]))
            {
                builder.Insert(0, ConstantSeparator);
            }

            return builder.ToString();
        }

        private static void AppendSeparator(StringBuilder builder)
        {
            if (builder.Length == 0 || builder[builder.Length - 1] == ConstantSeparator) return;

            builder.Append(ConstantSeparator);
        }

        private static string Escape(string value) => value.Replace(Backslash, EscapedBackslash).Replace(Quote, EscapedQuote);

        #endregion

        #region Texture Packer

        public static string WriteTexturePackerJson(KEmojiAtlas.Result atlas, string atlasPath)
        {
            var cellSize = KEmoji.CellSize;

            var document = new Document
            {
                frames = new List<Frame>(atlas.Placements.Count),
                meta = new Meta
                {
                    app = GeneratorName,
                    version = DocumentVersion,
                    image = Path.GetFileName(atlasPath),
                    format = PixelFormat,
                    size = new Size { w = atlas.Width, h = atlas.Height },
                    scale = DocumentScale,
                },
            };

            for (var i = 0; i < atlas.Placements.Count; i++)
            {
                var placement = atlas.Placements[i];

                document.frames.Add(new Frame
                {
                    filename = placement.Name + PngExtension,
                    frame = new Box { x = placement.X, y = ToTopDownY(placement.Y, atlas.Height, cellSize), w = cellSize, h = cellSize },
                    rotated = false,
                    trimmed = false,
                    spriteSourceSize = new Box { x = NoOffset, y = NoOffset, w = cellSize, h = cellSize },
                    sourceSize = new Size { w = cellSize, h = cellSize },
                    pivot = new Pivot { x = CenterPivot, y = CenterPivot },
                });
            }

            var jsonPath = Path.ChangeExtension(atlasPath, JsonExtension).NormalizeSlashes();

            File.WriteAllText(jsonPath.ToAbsolutePath(), JsonUtility.ToJson(document, true));

            AssetDatabase.ImportAsset(jsonPath);

            return jsonPath;
        }

        private static int ToTopDownY(int y, int atlasHeight, int cellSize) => atlasHeight - cellSize - y;

        #endregion

        #region Nested Type

        [Serializable]
        private class Size
        {
            public int w;
            public int h;
        }

        [Serializable]
        private class Pivot
        {
            public float x;
            public float y;
        }

        [Serializable]
        private class Box
        {
            public int x;
            public int y;
            public int w;
            public int h;
        }

        [Serializable]
        private class Frame
        {
            public string filename;
            public Box frame;
            public bool rotated;
            public bool trimmed;
            public Box spriteSourceSize;
            public Size sourceSize;
            public Pivot pivot;
        }

        [Serializable]
        private class Meta
        {
            public string app;
            public string version;
            public string image;
            public string format;
            public Size size;
            public string scale;
        }

        [Serializable]
        private class Document
        {
            public List<Frame> frames;
            public Meta meta;
        }

        #endregion
    }
}
#endif
